defaults:
 - lora_config: cfit_lora

mode: classifier

seed: 1
gpu_list: [0]

# model
name: vit
img_input_size: 512
text_input_size: 512
clip_path: "/home/taosiyuan/Giws/giws/CFIT/model/pretrained/clip_cn_rn50.pt"

# data
shuffle: false
k_fold: false
folds: 5
fold_index: 0

# train
train_batch_size: 128
accumulate_step: 4
train_data_folder: "/home/taosiyuan/DataSet/train" 
epochs: 2000

# accelerate
amp: true

# optimizer
learning_rate: 0.001 
max_grad_norm: 1.0

# output
output_dir: "/home/taosiyuan/Giws/output/vit" 
save_step: 500 

# logger
verbose: False

# eval
eval: true
eval_step: 5
test_data_folder: "/home/taosiyuan/DataSet/test" 
test_batch_size: 56 

# lora
apply_lora: true
