defaults:
 - lora_config: cfit_lora

mode: classifier

device: 0

# model
input_size: 2048
clip_path: "/home/taosiyuan/Giws/giws/CFIT/model/pretrained/clip_cn_rn50.pt"

# train
train_batch_size: 128
accumulate_step: 4
train_data_folder: "/home/taosiyuan/DataSet/train" 
epochs: 1000 

# accelerate
amp: true

# optimizer
learning_rate: 0.001 
max_grad_norm: 1.0

# output
output_dir: "/home/taosiyuan/Giws/output" 
save_step: 500 

# logger
verbose: False

# eval
eval: true
eval_step: 10
test_data_folder: "/home/taosiyuan/DataSet/test" 
test_batch_size: 56 

# lora
apply_lora: true
