defaults:
 - model: default

target: minst

# custom
gpu_id: 0
seed: 42
verbose: false

# training
epochs: 3
batch_size: 256
lr: 1e-3

# gradient clip
clip_grad: true
clip_mode: "norm"
clip_grad_value: 1.0

# eval and save
eval: true
eval_interval: 1
save_interval: 1
output_dir: ./trainer_output