defaults:
 - model: lstm

target: lstm
verbose: false
use_gpu: true

max_len: 1000

data_path: ../data/tang.npz
model_path: /mnt/user/taosiyuan/projects/Giws/trainer_output/lstm/20250526_150455/checkpoints/checkpoint_step_20300.ckpt

output_dir: ./inference_output/

