defaults:
 - model: lstm

target: lstm

# ref: https://github.com/tmatha/lstm/blob/master/lstm_tf.ipynb

# general
gpu_id: 0
seed: 42
verbose: false

# training
model_path: /mnt/user/taosiyuan/projects/data/best_checkpoint_epoch_22.ckpt
warm_start: false
data_path: /mnt/user/taosiyuan/projects/data/simple-examples/data
seq_len: 256
epochs: 50
batch_size: 512
lr: 0.001

# optim
schedule_type: 'cosine'
optim:
  is_cycle: true
  total_steps: 1000
  min_lr: 5e-5

# gradient clip
clip_grad: false
clip_mode: "norm"
clip_grad_value: 1.0

# amp
amp_enabled: false

# eval and save
eval: true
eval_interval: 1
save_interval: 100
output_dir: ./trainer_output/lstm