defaults:
 - model: lstm
 - custom: single

target: lstm

# custom
gpu_id: 0
seed: 42
verbose: false

# training
data_path: ../data/tang.npz
epochs: 500
batch_size: 256
lr: 3e-4

# gradient clip
clip_grad: true
clip_mode: "norm"
clip_grad_value: 1.0

# amp
amp_enabled: false

# eval and save
eval: true
eval_interval: 1
save_interval: 100
output_dir: ./trainer_output/lstm