defaults:
 - model: vit

target: vit

gpu_id: 0
seed: 42
verbose: false

data_path: ../data

# ref: https://github.com/kentaroy47/vision-transformers-cifar10/blob/main/train_cifar10.py
epochs: 500
batch_size: 512
lr: 1e-4
# gradients
clip_grad: true
clip_mode: "norm"
clip_grad_value: 1.0
# amp
amp_enabled: true


# eval
eval: true
eval_interval: 1


save_interval: 10
output_dir: ./trainer_output/vit