defaults:
 - model: transformer

target: transformer

use_gpu: true
gpu_list: [0,1,2,3]
seed: 42
verbose: false


# task specific
max_len: 512

# training
epochs: 500
batch_size: 64
lr: 1e-4
data_path: /mnt/user/taosiyuan/projects/data/sample-submission-version/TM-training-set
# gradients
clip_grad: true
clip_mode: "norm"
clip_grad_value: 1.0
# amp
amp_enabled: true


# eval
eval: true
eval_data_path: /mnt/user/taosiyuan/projects/data/sample-submission-version/Dev-set
eval_interval: 1

save_interval: 20
output_dir: ./trainer_output/transformer